services:
  - type: web
    name: promptslabs-ai
    env: node
    buildCommand: npm install
    startCommand: npm run render-start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    disk:
      name: promptslabs-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
